CREATE TABLE USERS
(
USER_ID INTEGER,
NAME VARCHAR(20),
JOIN_DATE DATE
);
INSERT INTO USERS
VALUES (1, 'JON', CAST('2-14-20' AS DATE)), 
(2, 'JANE', CAST('2-14-20' AS DATE)), 
(3, 'JILL', CAST('2-15-20' AS DATE)), 
(4, 'JOSH', CAST('2-15-20' AS DATE)), 
(5, 'JEAN', CAST('2-16-20' AS DATE)), 
(6, 'JUSTIN', CAST('2-17-20' AS DATE)),
(7, 'JEREMY', CAST('2-18-20' AS DATE));

CREATE TABLE EVENTS
(
USER_ID INTEGER,
TYPE VARCHAR(10),
ACCESS_DATE DATE
);

INSERT INTO EVENTS VALUES
(1, 'PAY', CAST('3-1-20' AS DATE)), 
(2, 'MUSIC', CAST('3-2-20' AS DATE)), 
(2, 'P', CAST('3-12-20' AS DATE)),
(3, 'MUSIC', CAST('3-15-20' AS DATE)), 
(4, 'MUSIC', CAST('3-15-20' AS DATE)), 
(1, 'P', CAST('3-16-20' AS DATE)), 
(3, 'P', CAST('3-22-20' AS DATE));

SELECT * FROM EVENTS;

SELECT * FROM USERS;

WITH CONSOLIDATED_DATA AS (SELECT E.USER_ID,U.NAME,U.JOIN_DATE,E.TYPE,E.ACCESS_DATE
, LEAD(TYPE) OVER(PARTITION BY E.USER_ID ORDER BY ACCESS_DATE) AS NXT_ACTION,COUNT(E.USER_ID) OVER(PARTITION BY TYPE) AS TOTAL_PRIME_CUST
FROM USERS U JOIN EVENTS E 
ON U.USER_ID=E.USER_ID 
WHERE DATEDIFF(DAY,JOIN_DATE,ACCESS_DATE)<30 AND TYPE IN ('MUSIC','P'))
, PRIME_UPGRADE AS(
SELECT * ,LEAD(ACCESS_DATE) OVER(PARTITION BY USER_ID ORDER BY ACCESS_DATE) AS UPGRADE_DATE
 FROM CONSOLIDATED_DATA
)
--SELECT USER_ID,NAME,TOTAL_PRIME_CUST FROM PRIME_UPGRADE WHERE DATEDIFF(DAY,ACCESS_DATE,UPGRADE_DATE) <30
SELECT CAST(ROUND(CAST(CAST(COUNT(USER_ID) OVER() AS FLOAT)/CAST(TOTAL_PRIME_CUST AS FLOAT) AS FLOAT),2) AS DECIMAL (36,2)) FROM PRIME_UPGRADE WHERE DATEDIFF(DAY,ACCESS_DATE,UPGRADE_DATE) <30
