CREATE TABLE USERS (
USER_ID         INT     ,
 JOIN_DATE       DATE    ,
 FAVORITE_BRAND  VARCHAR(50));

 CREATE TABLE ORDERS (
 ORDER_ID       INT     ,
 ORDER_DATE     DATE    ,
 ITEM_ID        INT     ,
 BUYER_ID       INT     ,
 SELLER_ID      INT 
 );

 CREATE TABLE ITEMS
 (
 ITEM_ID        INT     ,
 ITEM_BRAND     VARCHAR(50)
 );


 INSERT INTO USERS VALUES (1,'2019-01-01','LENOVO'),(2,'2019-02-09','SAMSUNG'),(3,'2019-01-19','LG'),(4,'2019-05-21','HP');

 INSERT INTO ITEMS VALUES (1,'SAMSUNG'),(2,'LENOVO'),(3,'LG'),(4,'HP');

 INSERT INTO ORDERS VALUES (1,'2019-08-01',4,1,2),(2,'2019-08-02',2,1,3),(3,'2019-08-03',3,2,3),(4,'2019-08-04',1,4,2)
 ,(5,'2019-08-04',1,3,4),(6,'2019-08-05',2,2,4);
 
 SELECT * FROM USERS;
 
 SELECT * FROM ITEMS;
 
 SELECT * FROM ORDERS;
 
 SELECT O.ORDER_ID,O.ORDER_DATE,U.USER_ID,I.ITEM_BRAND,U.FAVORITE_BRAND,ROW_NUMBER() OVER (PARTITION BY SELLER_ID ORDER BY ORDER_DATE ASC) AS RN
 FROM USERS U
LEFT JOIN ORDERS O ON O.SELLER_ID=U.USER_ID
LEFT JOIN ITEMS I ON O.ITEM_ID=I.ITEM_ID;
 
WITH COLLECTED_DATA AS (
SELECT O.ORDER_ID,O.ORDER_DATE,U.USER_ID,I.ITEM_BRAND,U.FAVORITE_BRAND,ROW_NUMBER() OVER (PARTITION BY SELLER_ID ORDER BY ORDER_DATE ASC) AS RN
,COUNT(USER_ID) OVER (PARTITION BY USER_ID) AS CNT
FROM USERS U
LEFT JOIN ORDERS O ON O.SELLER_ID=U.USER_ID
LEFT JOIN ITEMS I ON O.ITEM_ID=I.ITEM_ID
)
SELECT USER_ID, CASE WHEN ITEM_BRAND=FAVORITE_BRAND THEN 'YES' ELSE 'NO' END AS FAVORITE_BRAND FROM COLLECTED_DATA WHERE RN=2 OR CNT=1;
