CREATE TABLE KING (
    K_NO INT PRIMARY KEY,
    KING VARCHAR(50),
    HOUSE VARCHAR(50)
);

-- CREATE THE 'BATTLE' TABLE
CREATE TABLE BATTLE (
    BATTLE_NUMBER INT PRIMARY KEY,
    NAME VARCHAR(100),
    ATTACKER_KING INT,
    DEFENDER_KING INT,
    ATTACKER_OUTCOME INT,
    REGION VARCHAR(50),
    FOREIGN KEY (ATTACKER_KING) REFERENCES KING(K_NO),
    FOREIGN KEY (DEFENDER_KING) REFERENCES KING(K_NO)
);

DELETE FROM KING;
INSERT INTO KING (K_NO, KING, HOUSE) VALUES
(1, 'ROBB STARK', 'HOUSE STARK'),
(2, 'JOFFREY BARATHEON', 'HOUSE LANNISTER'),
(3, 'STANNIS BARATHEON', 'HOUSE BARATHEON'),
(4, 'BALON GREYJOY', 'HOUSE GREYJOY'),
(5, 'MACE TYRELL', 'HOUSE TYRELL'),
(6, 'DORAN MARTELL', 'HOUSE MARTELL');

DELETE FROM BATTLE;
-- INSERT DATA INTO THE 'BATTLE' TABLE
INSERT INTO BATTLE (BATTLE_NUMBER, NAME, ATTACKER_KING, DEFENDER_KING, ATTACKER_OUTCOME, REGION) VALUES
(1, 'BATTLE OF OXCROSS', 1, 2, 1, 'THE NORTH'),
(2, 'BATTLE OF BLACKWATER', 3, 4, 0, 'THE NORTH'),
(3, 'BATTLE OF THE FORDS', 1, 5, 1, 'THE REACH'),
(4, 'BATTLE OF THE GREEN FORK', 2, 6, 0, 'THE REACH'),
(5, 'BATTLE OF THE RUBY FORD', 1, 3, 1, 'THE RIVERLANDS'),
(6, 'BATTLE OF THE GOLDEN TOOTH', 2, 1, 0, 'THE NORTH'),
(7, 'BATTLE OF RIVERRUN', 3, 4, 1, 'THE RIVERLANDS'),
(8, 'BATTLE OF RIVERRUN', 1, 3, 0, 'THE RIVERLANDS');
--FOR EACH REGION FIND HOUSE WHICH HAS WON MAXIMUM NO OF BATTLES. DISPLAY REGION, HOUSE AND NO OF WINS
SELECT * FROM BATTLE;
SELECT * FROM KING;

WITH WINNERS AS (
SELECT B.REGION,A.KING,A.HOUSE AS WINNER_HOUSE FROM BATTLE B JOIN KING A ON B.ATTACKER_KING=A.K_NO WHERE ATTACKER_OUTCOME=1
UNION ALL
SELECT B.REGION,A.KING,A.HOUSE AS WINNER_HOUSE FROM BATTLE B JOIN KING A ON B.DEFENDER_KING=A.K_NO WHERE ATTACKER_OUTCOME=0
)
,REGION_WISE_STATS AS(
SELECT COUNT(1) AS TOTAL_WINS,REGION,WINNER_HOUSE FROM WINNERS GROUP BY REGION,WINNER_HOUSE
)
, RANKS AS (
SELECT DENSE_RANK() OVER(PARTITION BY REGION ORDER BY TOTAL_WINS DESC) AS RN,* 
FROM REGION_WISE_STATS)
SELECT REGION,WINNER_HOUSE AS HOUSE, TOTAL_WINS AS NO_OF_WINS FROM RANKS WHERE RN=1;
